import { invoke } from './api.service';

/**
 * Universal Generic API Service for `tauri-surreal-kit`.
 * 
 * Automatically connects to the Rust backend commands generated by the `#[surreal_entity]` macro.
 * 
 * @example
 * // In Rust:
 * // #[surreal_entity(table = "users")]
 * // pub struct User { ... }
 * 
 * // In Vue/TypeScript:
 * import { EntityService } from '../services/entity.service';
 * interface User { id?: string; name: string; }
 * 
 * const userApi = new EntityService<User>('user');
 * const allUsers = await userApi.getAll('projects:123');
 */
export class EntityService<T> {
  private entityName: string;
  private entityPlural: string;

  /**
   * @param entityName The singular name of the struct in Rust (e.g., 'user', 'chapter', 'article')
   * @param entityPlural Optional plural name. Defaults to entityName + 's'.
   */
  constructor(entityName: string, entityPlural?: string) {
    this.entityName = entityName.toLowerCase();
    this.entityPlural = entityPlural ? entityPlural.toLowerCase() : `${this.entityName}s`;
  }

  /** Fetch all entities of this type for a specific project */
  async getAll(project: string): Promise<T[]> {
    try {
      const res = await invoke<T[]>(`get_${this.entityPlural}`, { project });
      return res || [];
    } catch (e) {
      console.error(`[EntityService] getAll(${this.entityName}) error:`, e);
      return [];
    }
  }

  /** Fetch a single entity by its ID */
  async getOne(id: string): Promise<T | null> {
    try {
      const res = await invoke<T>(`get_${this.entityName}`, { id });
      return res || null;
    } catch (e) {
      console.error(`[EntityService] getOne(${this.entityName}) error:`, e);
      return null;
    }
  }

  /** Create or Update an entity (Upsert) */
  async save(data: Partial<T>): Promise<T | null> {
    try {
      const res = await invoke<T>(`save_${this.entityName}`, { data });
      return res || null;
    } catch (e) {
      console.error(`[EntityService] save(${this.entityName}) error:`, e);
      return null;
    }
  }

  /** Delete an entity by ID */
  async delete(id: string): Promise<boolean> {
    try {
      await invoke(`delete_${this.entityName}`, { id });
      return true;
    } catch (e) {
      console.error(`[EntityService] delete(${this.entityName}) error:`, e);
      return false;
    }
  }

  /** 
   * Search entities (Requires `#[fulltext]` attribute on fields in Rust)
   */
  async search(project: string, query: string): Promise<{entity: T, score: number}[]> {
    try {
      const res = await invoke<any[]>(`search_${this.entityPlural}`, { project, query });
      return res || [];
    } catch (e) {
      console.error(`[EntityService] search(${this.entityName}) error:`, e);
      return [];
    }
  }
}
